// GENERATED BY...
// original - https://stackblitz.com/edit/chart-color-generator?file=index.js
// base - https://stackblitz.com/edit/chart-color-generator-yuzpod?file=index.js
// solid - https://stackblitz.com/edit/chart-color-generator-4hi5b9?file=index.js

export const CHART_COLORS: string[] = [
  'rgb(42.487% 43.674% 77.307%)',
  'rgb(54.856% 28.66% 56.547%)',
  'rgb(95.77% 53.351% 60.514%)',
  'rgb(84.469% 50.392% 24.719%)',
  'rgb(59.928% 52.542% 0%)',
  'rgb(20.324% 52.569% 23.201%)',
  'rgb(0% 44.54% 42.576%)',
  'rgb(19.21% 69.515% 93.581%)',
  'rgb(50.578% 52.114% 89.374%)',
  'rgb(65.124% 36.12% 66.947%)',
  'rgb(67.145% 24.704% 34.106%)',
  'rgb(52.126% 26.072% 0%)',
  'rgb(69.611% 61.544% 0%)',
  'rgb(27.225% 62.166% 29.924%)',
  'rgb(0% 54.173% 51.865%)',
  'rgb(0% 41.59% 62.59%)',
  'rgb(58.918% 60.797% 100%)',
  'rgb(75.69% 43.813% 77.649%)',
  'rgb(78.739% 32.073% 41.889%)',
  'rgb(63.779% 33.128% 0%)',
  'rgb(41.995% 35.038% 0%)',
  'rgb(34.223% 72.038% 36.832%)',
  'rgb(0% 64.141% 61.477%)',
  'rgb(0% 50.784% 74.912%)',
  'rgb(33.808% 32.891% 73.928%)',
  'rgb(86.532% 51.724% 88.629%)',
  'rgb(90.637% 39.616% 49.935%)',
  'rgb(77.467% 39.274% 0%)',
  'rgb(51.365% 43.467% 0%)',
  'rgb(0% 45.004% 3.8284%)',
  'rgb(0% 74.403% 71.372%)',
  'rgb(0% 60.283% 87.705%)',
];

export const CHART_SOLID_COLORS: string[] = [
  'rgb(54.146% 56.122% 88.156%)',
  'rgb(66.102% 41.379% 67.521%)',
  'rgb(100% 68.969% 74.086%)',
  'rgb(95.821% 63.756% 41.241%)',
  'rgb(71.295% 64.777% 24.805%)',
  'rgb(35.893% 64.024% 37.231%)',
  'rgb(0% 57.115% 54.77%)',
  'rgb(43.092% 81.8% 100%)',
  'rgb(62.798% 65.104% 99.308%)',
  'rgb(76.117% 49.696% 77.582%)',
  'rgb(77.81% 39.168% 46.171%)',
  'rgb(67.075% 36.207% 10.048%)',
  'rgb(80.966% 74.112% 32.611%)',
  'rgb(43.918% 73.645% 45.132%)',
  'rgb(0% 66.973% 64.304%)',
  'rgb(0% 53.88% 75.416%)',
  'rgb(73.141% 74.699% 100%)',
  'rgb(86.372% 58.238% 87.886%)',
  'rgb(88.736% 47.436% 54.624%)',
  'rgb(77.573% 44.558% 18.791%)',
  'rgb(53.734% 46.641% 0%)',
  'rgb(52.119% 83.498% 53.242%)',
  'rgb(0% 76.758% 73.813%)',
  'rgb(12.721% 63.169% 86.107%)',
  'rgb(45.104% 46.37% 81.66%)',
  'rgb(96.851% 66.992% 98.416%)',
  'rgb(99.891% 55.91% 63.32%)',
  'rgb(88.312% 53.132% 26.787%)',
  'rgb(63.075% 55.522% 0%)',
  'rgb(23.029% 55.664% 25.719%)',
  'rgb(5.885% 86.771% 83.554%)',
  'rgb(23.186% 72.694% 97.04%)',
];

export const CHART_COLORS_MAP = {
  blue: CHART_COLORS[0],
  green: CHART_COLORS[13],
  red: CHART_COLORS[10],
  orange: CHART_COLORS[3],
  purple: CHART_COLORS[1],
  yellow: CHART_COLORS[4],
  cyan: CHART_COLORS[30],
  magenta: CHART_COLORS[25],
};

export const CHART_SOLID_COLORS_MAP = {
  blue: CHART_SOLID_COLORS[0],
  green: CHART_SOLID_COLORS[13],
  red: CHART_SOLID_COLORS[10],
  orange: CHART_SOLID_COLORS[3],
  purple: CHART_SOLID_COLORS[1],
  yellow: CHART_SOLID_COLORS[4],
  cyan: CHART_SOLID_COLORS[30],
  magenta: CHART_SOLID_COLORS[25],
};

export function getChartColorByIndex(index: number) {
  return CHART_COLORS[index % CHART_COLORS.length];
}

export function getChartSolidColorByIndex(index: number) {
  return CHART_SOLID_COLORS[index % CHART_COLORS.length];
}
