version: '3'

services:
  coordinator:
    image: lewuathe/presto-coordinator:340-SNAPSHOT
    ports:
      - "8080:8080"
    container_name: "coordinator"
    depends_on:
      - postgres
    links:
      - postgres
    command: http://coordinator:8080 coordinator
    volumes:
      - ./config/catalog/:/usr/local/presto/etc/catalog/

  worker0:
    image: lewuathe/presto-worker:340-SNAPSHOT
    container_name: "worker0"
    depends_on:
      - coordinator
      - postgres
    links:
      - coordinator
      - postgres
    command: http://coordinator:8080 worker0
    volumes:
      - ./config/catalog/:/usr/local/presto/etc/catalog/
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8081/ || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5

  worker1:
    image: lewuathe/presto-worker:340-SNAPSHOT
    container_name: "worker1"
    depends_on:
      - coordinator
      - postgres
    links:
      - coordinator
      - postgres
    command: http://coordinator:8080 worker1
    volumes:
      - ./config/catalog/:/usr/local/presto/etc/catalog/
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8081/ || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:12.4
    environment:
      POSTGRES_USER: 'presto'
      POSTGRES_PASSWORD: '9bee2c3975024292eff5829526722ac2'
      POSTGRES_DB: 'presto'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U presto"]
      interval: 10s
      timeout: 5s
      retries: 5
