"help wanted":
    comment: |
        If you are interested in working on this issue, please provide go ahead and provide PR for that.
        We'd be happy to review it and merge it.
        If this is the first time you are contributing a Pull Request to Cube, please check our [contribution guidelines](https://github.com/cube-js/cube/blob/master/CONTRIBUTING.md).
        You can also post any questions while contributing in the #contributors channel in the [Cube Slack](https://slack.cube.dev/).
