FROM node:20-bullseye

WORKDIR /app
RUN mkdir -p /app/core

WORKDIR /app/core
COPY . .
RUN yarn install && \
    yarn build && \
    cd packages/cubejs-playground && \
    yarn build && \
    cd ../.. && \
    yarn tsc

RUN cd "packages/cubejs-postgres-driver" && \
    yarn link && \
    yarn install && \
    cd ../../packages/cubejs-server-core && \
    yarn link "@cubejs-backend/postgres-driver" && \
    cd ../../packages/cubejs-server-core && \
    yarn link

WORKDIR /app
RUN npx cubejs-cli create "CubeDevDocker" -d "postgres" && \
    cd "CubeDevDocker" && \
    yarn link @cubejs-backend/server-core
WORKDIR /app/CubeDevDocker
CMD [ "yarn", "dev" ]