[package]
name = "cubedatasketch"
version = "0.1.0"
authors = ["Cube Dev, Inc."]
edition = "2018"
license = "Apache-2.0"
description = "HyperLogLog++ implementation ported from ZetaSketch"

[dependencies]
dsrs = { git = "https://github.com/cube-js/datasketches-rs.git", branch = "cubestore" }
