/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1CubeMetaFolderMembersInner {
    String(String),
    V1CubeMetaFolder(Box<crate::models::V1CubeMetaFolder>),
}

impl Default for V1CubeMetaFolderMembersInner {
    fn default() -> Self {
        Self::String(Default::default())
    }
}
