/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1CubeMetaDimensionFormat : Format of dimension - can be either a simple string format or an object with link configuration
/// Format of dimension - can be either a simple string format or an object with link configuration
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Eq, Hash, PartialOrd, Ord)]
#[serde(untagged)]
pub enum V1CubeMetaDimensionFormat {
    V1CubeMetaDimensionSimpleFormat(models::V1CubeMetaDimensionSimpleFormat),
    V1CubeMetaDimensionLinkFormat(Box<models::V1CubeMetaDimensionLinkFormat>),
}

impl Default for V1CubeMetaDimensionFormat {
    fn default() -> Self {
        Self::V1CubeMetaDimensionSimpleFormat(Default::default())
    }
}
/// Type of the format (must be 'link')
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "link")]
    Link,
}

impl Default for Type {
    fn default() -> Type {
        Self::Link
    }
}
