/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1CubeMetaCustomTimeFormat : Custom time format for time dimensions
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1CubeMetaCustomTimeFormat {
    /// Type of the format (must be 'custom-time')
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Time format string (e.g., 'yyyy-MM-dd', 'dd/mm/yyyy hh:nn:ss')
    #[serde(rename = "value")]
    pub value: String,
}

impl V1CubeMetaCustomTimeFormat {
    /// Custom time format for time dimensions
    pub fn new(r#type: Type, value: String) -> V1CubeMetaCustomTimeFormat {
        V1CubeMetaCustomTimeFormat { r#type, value }
    }
}
/// Type of the format (must be 'custom-time')
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "custom-time")]
    CustomTime,
}

impl Default for Type {
    fn default() -> Type {
        Self::CustomTime
    }
}
