/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1CubeMetaHierarchy {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "levels")]
    pub levels: Vec<String>,
}

impl V1CubeMetaHierarchy {
    pub fn new(name: String, levels: Vec<String>) -> V1CubeMetaHierarchy {
        V1CubeMetaHierarchy {
            name,
            title: None,
            levels,
        }
    }
}
