/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1CubeMetaMeasureFormat : Format of measure
/// Format of measure
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum V1CubeMetaMeasureFormat {
    #[serde(rename = "percent")]
    Percent,
    #[serde(rename = "currency")]
    Currency,
}

impl std::fmt::Display for V1CubeMetaMeasureFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Percent => write!(f, "percent"),
            Self::Currency => write!(f, "currency"),
        }
    }
}

impl Default for V1CubeMetaMeasureFormat {
    fn default() -> V1CubeMetaMeasureFormat {
        Self::Percent
    }
}
