/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1CubeMetaCustomDateFormat : Custom date format for time dimensions
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1CubeMetaCustomDateFormat {
    /// Type of the format (must be 'custom-date')
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Date format string (e.g., 'yyyy-MM-dd', 'dd/mm/yyyy hh:nn:ss')
    #[serde(rename = "value")]
    pub value: String,
}

impl V1CubeMetaCustomDateFormat {
    /// Custom date format for time dimensions
    pub fn new(r#type: Type, value: String) -> V1CubeMetaCustomDateFormat {
        V1CubeMetaCustomDateFormat { r#type, value }
    }
}
/// Type of the format (must be 'custom-date')
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "custom-date")]
    CustomDate,
}

impl Default for Type {
    fn default() -> Type {
        Self::CustomDate
    }
}
