/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1CubeMeta {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "measures")]
    pub measures: Vec<crate::models::V1CubeMetaMeasure>,
    #[serde(rename = "dimensions")]
    pub dimensions: Vec<crate::models::V1CubeMetaDimension>,
    #[serde(rename = "segments")]
    pub segments: Vec<crate::models::V1CubeMetaSegment>,
    #[serde(rename = "joins", skip_serializing_if = "Option::is_none")]
    pub joins: Option<Vec<crate::models::V1CubeMetaJoin>>,
}

impl V1CubeMeta {
    pub fn new(
        name: String,
        measures: Vec<crate::models::V1CubeMetaMeasure>,
        dimensions: Vec<crate::models::V1CubeMetaDimension>,
        segments: Vec<crate::models::V1CubeMetaSegment>,
        joins: Option<Vec<crate::models::V1CubeMetaJoin>>,
    ) -> V1CubeMeta {
        V1CubeMeta {
            name,
            title: None,
            measures,
            dimensions,
            segments,
            joins,
        }
    }
}
