/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1CubeMetaDimensionSimpleFormat : Simple format of dimension
/// Simple format of dimension
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum V1CubeMetaDimensionSimpleFormat {
    #[serde(rename = "imageUrl")]
    ImageUrl,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "link")]
    Link,
    #[serde(rename = "percent")]
    Percent,
    #[serde(rename = "currency")]
    Currency,
}

impl std::fmt::Display for V1CubeMetaDimensionSimpleFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ImageUrl => write!(f, "imageUrl"),
            Self::Id => write!(f, "id"),
            Self::Link => write!(f, "link"),
            Self::Percent => write!(f, "percent"),
            Self::Currency => write!(f, "currency"),
        }
    }
}

impl Default for V1CubeMetaDimensionSimpleFormat {
    fn default() -> V1CubeMetaDimensionSimpleFormat {
        Self::ImageUrl
    }
}
