/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1CubeMetaType : Type of cube
/// Type of cube
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum V1CubeMetaType {
    #[serde(rename = "cube")]
    Cube,
    #[serde(rename = "view")]
    View,
}

impl std::fmt::Display for V1CubeMetaType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Cube => write!(f, "cube"),
            Self::View => write!(f, "view"),
        }
    }
}

impl Default for V1CubeMetaType {
    fn default() -> V1CubeMetaType {
        Self::Cube
    }
}
