/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1LoadRequestQueryFilterItem {
    V1LoadRequestQueryFilterBase(Box<models::V1LoadRequestQueryFilterBase>),
    V1LoadRequestQueryFilterLogicalOr(Box<models::V1LoadRequestQueryFilterLogicalOr>),
    V1LoadRequestQueryFilterLogicalAnd(Box<models::V1LoadRequestQueryFilterLogicalAnd>),
}

impl Default for V1LoadRequestQueryFilterItem {
    fn default() -> Self {
        Self::V1LoadRequestQueryFilterBase(Default::default())
    }
}
