/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1LoadRequestQueryJoinSubquery {
    #[serde(rename = "sql")]
    pub sql: String,
    #[serde(rename = "on")]
    pub on: String,
    #[serde(rename = "joinType")]
    pub join_type: String,
    #[serde(rename = "alias")]
    pub alias: String,
}

impl V1LoadRequestQueryJoinSubquery {
    pub fn new(
        sql: String,
        on: String,
        join_type: String,
        alias: String,
    ) -> V1LoadRequestQueryJoinSubquery {
        V1LoadRequestQueryJoinSubquery {
            sql,
            on,
            join_type,
            alias,
        }
    }
}
