/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MetaResponse {
    #[serde(rename = "cubes", skip_serializing_if = "Option::is_none")]
    pub cubes: Option<Vec<models::V1CubeMeta>>,
    #[serde(rename = "compilerId", skip_serializing_if = "Option::is_none")]
    pub compiler_id: Option<String>,
}

impl V1MetaResponse {
    pub fn new() -> V1MetaResponse {
        V1MetaResponse {
            cubes: None,
            compiler_id: None,
        }
    }
}
