// Generated by the FlatBuffers compiler — silence clippy on the generated module.
#[allow(unused_imports, clippy::all, clippy::pedantic, clippy::nursery)]
mod http_message_generated;

pub use http_message_generated::*;
