// Repro for https://github.com/cube-js/cube/issues/7006
//
// `DATE(col) BETWEEN DATE('a') AND DATE('b')` (as generated by Metabase, Grafana, etc.)
// is rewritten by the SQL API into an `inDateRange` filter whose upper bound is
// `b` at midnight (`bT00:00:00.000Z`). Cube treats that as an instant, so rows later
// in the day `b` are dropped, while the SQL semantics include the whole day `b`.
// The equivalent `DATE(col) >= DATE('a') AND DATE(col) <= DATE('b')` and
// `DATE(col) BETWEEN 'a' AND 'b'` keep the whole last day.
import { Writable } from 'stream';

import * as native from '../js';
import metaFixture from './meta';

function interfaceMethods(loadQueries: any[]) {
  const errorResponse = async ({ query }: any) => {
    loadQueries.push(query);
    return { error: 'issue-7006: load is not implemented in this test' };
  };

  return {
    sqlApiLoad: jest.fn(errorResponse),
    sql: jest.fn(async () => ({ error: 'issue-7006: sql is not implemented in this test' })),
    stream: jest.fn(errorResponse),
    meta: jest.fn(async () => metaFixture),
    sqlGenerators: jest.fn(async () => ({
      cubeNameToDataSource: {},
      memberToDataSource: {},
      dataSourceToSqlGenerator: {},
    })),
    contextToApiScopes: jest.fn(async () => ['data', 'meta', 'graphql']),
    checkAuth: jest.fn(async () => {
      throw new Error('checkAuth is not implemented');
    }),
    checkSqlAuth: jest.fn(async () => ({
      password: null,
      superuser: false,
      securityContext: {},
    })),
    logLoadEvent: () => undefined,
    canSwitchUserForSession: (_payload: any) => true,
  };
}

async function captureLoadQuery(sql: string): Promise<any> {
  const loadQueries: any[] = [];
  const instance = await native.registerInterface({
    ...interfaceMethods(loadQueries),
  } as any);

  try {
    const sink = new Writable({
      write(_chunk, _encoding, callback) {
        callback();
      },
    });

    try {
      await native.execSql(instance, sql, sink);
    } catch {
      // The load callback returns an error on purpose: we only need the query
    }
  } finally {
    await native.shutdownInterface(instance, 'fast');
  }

  expect(loadQueries.length).toBeGreaterThan(0);
  return loadQueries[0];
}

function orderDateRange(query: any): string[] {
  const fromTimeDimensions = (query.timeDimensions || [])
    .filter((td: any) => td.dimension === 'KibanaSampleDataEcommerce.order_date' && td.dateRange);
  if (fromTimeDimensions.length) {
    return fromTimeDimensions[0].dateRange;
  }

  const fromFilters = (query.filters || [])
    .filter((f: any) => f.member === 'KibanaSampleDataEcommerce.order_date' && f.operator === 'inDateRange');
  expect(fromFilters.length).toEqual(1);
  return fromFilters[0].values;
}

// The inclusive upper bound must cover the whole day, i.e. either a bare date
// (which Cube expands to the end of the day) or the last millisecond of that day.
function expectCoversWholeDay(bound: string, day: string) {
  expect([day, `${day}T23:59:59.999`, `${day}T23:59:59.999Z`]).toContain(bound);
}

describe('issue-7006: DATE(col) BETWEEN DATE(a) AND DATE(b) in SQL API', () => {
  jest.setTimeout(60 * 1000);

  it('control: BETWEEN with string bounds keeps the whole last day', async () => {
    const query = await captureLoadQuery(
      'SELECT MEASURE(count) FROM KibanaSampleDataEcommerce ' +
      "WHERE DATE(order_date) BETWEEN '2024-02-01' AND '2024-03-31'"
    );

    expectCoversWholeDay(orderDateRange(query)[1], '2024-03-31');
  });

  it('BETWEEN with DATE() bounds keeps the whole last day', async () => {
    const query = await captureLoadQuery(
      'SELECT MEASURE(count) FROM KibanaSampleDataEcommerce ' +
      "WHERE DATE(order_date) BETWEEN DATE('2024-02-01') AND DATE('2024-03-31')"
    );

    expectCoversWholeDay(orderDateRange(query)[1], '2024-03-31');
  });
});
