version: "2.2"

services:
  cube:
    container_name: birdbox-cube
    image: ${BIRDBOX_CUBEJS_REGISTRY_PATH}cubejs/cube:${BIRDBOX_CUBEJS_VERSION:-latest}
    environment:
      CUBEJS_DB_TYPE: athena

      # from env
      CUBEJS_AWS_KEY: ${CUBEJS_AWS_KEY}
      CUBEJS_AWS_SECRET: ${CUBEJS_AWS_SECRET}
      CUBEJS_AWS_REGION: ${CUBEJS_AWS_REGION}
      CUBEJS_AWS_S3_OUTPUT_LOCATION: ${CUBEJS_AWS_S3_OUTPUT_LOCATION}
      CUBEJS_DB_EXPORT_BUCKET: ${CUBEJS_DB_EXPORT_BUCKET}

      # from test
      CUBEJS_SCHEDULED_REFRESH_DEFAULT: ${CUBEJS_SCHEDULED_REFRESH_DEFAULT}
      CUBEJS_REFRESH_WORKER: ${CUBEJS_REFRESH_WORKER}
      CUBEJS_EXTERNAL_DEFAULT: ${CUBEJS_EXTERNAL_DEFAULT}
      CUBEJS_ROLLUP_ONLY: ${CUBEJS_ROLLUP_ONLY}

      # defaults
      CUBEJS_DEV_MODE: "true"
      CUBEJS_API_SECRET: mysupersecret
    volumes:
      - ./postgresql/single/cube.js:/cube/conf/cube.js
      - ./postgresql/schema/OrdersPA.js:/cube/conf/schema/OrdersPA.js
    ports:
      - "4000:4000"
    restart: always
