version: "2.2"

services:
  cube:
    container_name: birdbox-cube
    image: ${BIRDBOX_CUBEJS_REGISTRY_PATH}cubejs/cube:${BIRDBOX_CUBEJS_VERSION:-latest}
    environment:
      CUBEJS_DB_TYPE: questdb
      CUBEJS_DB_HOST: db
      CUBEJS_DB_PORT: 8812
      CUBEJS_DB_NAME: qdb
      CUBEJS_DB_USER: admin
      CUBEJS_DB_PASS: quest
      CUBEJS_DEV_MODE: "true"
      CUBEJS_WEB_SOCKETS: "true"
      CUBEJS_API_SECRET: mysupersecret
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./questdb/schema:/cube/conf/schema
      - ./postgresql/dbt-project:/cube/conf/dbt-project
    ports:
      - "4000"
    restart: always

  db:
    container_name: birdbox-db
    image: questdb/questdb:6.2.1
    ports:
      - "8812"
      - "9000"
      - "9003"
    restart: always
    volumes:
      - ./datasets:/data:ro
      - ./questdb/scripts:/scripts:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:9003 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
