version: '2.2'

services:
  cube:
    image: cubejs/cube:latest
    ports:
      - ${CUBEJS_TEST_PORT}:4000
      - ${CUBESTORE_TEST_PORT}:3000
    environment:
      - CUBEJS_REFRESH_WORKER=false
      - CUBEJS_ROLLUP_ONLY=true

      - CUBEJS_DEV_MODE
      - CUBEJS_TEST_USE_LAMBDA

      - CUBEJS_DB_TYPE=bigquery
      - CUBEJS_DB_BQ_PROJECT_ID
      - CUBEJS_DB_BQ_CREDENTIALS
      - CUBEJS_DB_EXPORT_BUCKET

      - CUBEJS_EXT_DB_TYPE=cubestore
      - CUBEJS_EXT_DB_HOST=cubestore_router
      - CUBEJS_EXT_DB_PORT=3030

      - CUBEJS_REDIS_URL=redis://redis:6379
      
      - CUBEJS_API_SECRET=SECRET
    volumes:
      - .:/cube/conf
    depends_on:
      - cubestore_router
      - redis

  cubestore_router:
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002,cubestore_worker_3:10003,cubestore_worker_4:10004
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_PORT=9999
      - CUBESTORE_SERVER_NAME=cubestore_router:9999
    volumes:
      - .cubestore/${CUBESTORE_DIR}:/cube/data

  cubestore_worker_1:
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002,cubestore_worker_3:10003,cubestore_worker_4:10004
      - CUBESTORE_SERVER_NAME=cubestore_worker_1:10001
      - CUBESTORE_WORKER_PORT=10001
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore/${CUBESTORE_DIR}:/cube/data
    depends_on:
      - cubestore_router

  cubestore_worker_2:
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002,cubestore_worker_3:10003,cubestore_worker_4:10004
      - CUBESTORE_SERVER_NAME=cubestore_worker_2:10002
      - CUBESTORE_WORKER_PORT=10002
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore/${CUBESTORE_DIR}:/cube/data
    depends_on:
      - cubestore_router

  cubestore_worker_3:
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002,cubestore_worker_3:10003,cubestore_worker_4:10004
      - CUBESTORE_SERVER_NAME=cubestore_worker_3:10003
      - CUBESTORE_WORKER_PORT=10003
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore/${CUBESTORE_DIR}:/cube/data
    depends_on:
      - cubestore_router

  cubestore_worker_4:
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002,cubestore_worker_3:10003,cubestore_worker_4:10004
      - CUBESTORE_SERVER_NAME=cubestore_worker_4:10004
      - CUBESTORE_WORKER_PORT=10004
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore/${CUBESTORE_DIR}:/cube/data
    depends_on:
      - cubestore_router

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    logging:
      driver: none 