version: "3"

services:
  cube:
    container_name: birdbox-cube
    image: cubejs/cube:latest
    environment:
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_HOST: postgres
      CUBEJS_DB_NAME: test
      CUBEJS_DB_USER: test
      CUBEJS_DB_PASS: test
      CUBEJS_DEV_MODE: "true"
      CUBEJS_API_SECRET: mysupersecret
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./postgresql/single/cube.js:/cube/conf/cube.js
      - ./postgresql/schema:/cube/conf/schema
    ports:
      - 4000
    restart: always

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U druid"]
      interval: 10s
      timeout: 5s
      retries: 5
