// DO NOT MANUALLY EDIT - THIS FILE IS AUTOMATICALLY GENERATED

export type IntrospectedMeasureName = string;
export type IntrospectedDimensionName = string;
export type IntrospectedTimeDimensionName = string;
export type IntrospectedSegmentName = string;
