[project]
name = "cube"
version = "0.0.1"
authors = [
  { name="Cube Dev, Inc.", email="hello@cube.dev" },
]
description = ""
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/cube-js/cube"
"Bug Tracker" = "https://github.com/cube-js/cube/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
