[workspace]
members = [
    "cubestore",
    "cubehll",
    "cubezetasketch",
    "cuberpc",
]

[patch.crates-io]
sqlparser = { git = 'https://github.com/cube-js/sqlparser-rs', branch = 'cubestore-2021-01-05' }
