[workspace]
resolver = "2"
members = [
    "cubestore",
    "cubestore-sql-tests",
    "cubehll",
    "cubezetasketch",
    "cuberpc",
]

[patch.crates-io]
sqlparser = { git = 'https://github.com/cube-js/sqlparser-rs', tag = 'v0.9.0-cube' }
