[target.x86_64-apple-darwin]
image = "cubejs/rust-cross:x86_64-apple-darwin"
xargo = true

[target.x86_64-pc-windows-gnu]
image = "cubejs/rust-cross:x86_64-pc-windows-gnu"
xargo = true

# [target.x86_64-unknown-linux-gnu]
# image = "cubejs/rust-cross:x86_64-unknown-linux-gnu"
# xargo = false

[target.x86_64-unknown-linux-musl]
image = "cubejs/rust-cross:x86_64-unknown-linux-musl"
xargo = true
