name: Deploy Example to Cube Cloud and Netlify

inputs:

  slug:
    required: true

  frontend-folder:
    required: false
    default: dashboard-app

runs:
  using: composite
  steps:

    - uses: pheel/path-watcher-action@v1
      id: modified
      with:
        paths: ${{ format('.github/workflows/examples.yml,examples/{0}/**', inputs.slug) }}

    - name: Use Node.js 14.x
      if: steps.modified.outputs.modified
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install Netlify CLI
      if: steps.modified.outputs.modified
      run: npm install -g netlify-cli

    - name: Install Cube.js CLI
      if: steps.modified.outputs.modified
      run: npm install -g cubejs-cli

    - name: Yarn install
      if: steps.modified.outputs.modified
      run: yarn install
      working-directory: ${{ format('examples/{0}', inputs.slug) }}

    - name: Deploy to Cube Cloud
      if: steps.modified.outputs.modified
      run: cubejs deploy
      working-directory: ${{ format('examples/{0}', inputs.slug) }}
      env:
        CUBE_CLOUD_DEPLOY_AUTH: ${{ secrets.CUBE_CLOUD_DEPLOY_AUTH }}

    - name: Yarn install
      if: steps.modified.outputs.modified
      run: yarn install
      working-directory: ${{ format('examples/{0}/{1}', inputs.slug, input.frontend-folder) }}

    - name: Yarn build
      if: steps.modified.outputs.modified
      run: yarn build
      working-directory: ${{ format('examples/{0}/{1}', inputs.slug, input.frontend-folder) }}

    - name: Deploy to Netlify
      if: steps.modified.outputs.modified
      run: netlify deploy --dir=dist/dashboard-app --prod
      working-directory: ${{ format('examples/{0}/{1}', inputs.slug, input.frontend-folder) }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}