apiVersion: v2
name: cube-stack
description: Cube Stack is an Umbrella Chart that contains everything needed to run Cube in production.
type: application
version: 0.1.0
appVersion: "0.28.26"
keywords:
- cubejs
maintainers:
  - name: Luc Vauvillier
    email: luc.vauvillier@gmail.com
  - name: Adnan Rahic
    email: adnan@cube.dev
sources:
  - https://github.com/cube-js/cube.js
dependencies:
- name: cubejs
  version: "0.1.*"
  repository: file://../cubejs
  condition: global.cubejs.enabled
- name: cubestore
  version: "0.1.*"
  repository: file://../cubestore
  condition: global.cubestore.enabled
- name: redis
  version: "~11.2"
  repository: "@bitnami"
  condition: global.redis.enabled
