// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { HttpColumnValue } from './http-column-value.js';


export class HttpRow {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):HttpRow {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsHttpRow(bb:flatbuffers.ByteBuffer, obj?:HttpRow):HttpRow {
  return (obj || new HttpRow()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsHttpRow(bb:flatbuffers.ByteBuffer, obj?:HttpRow):HttpRow {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new HttpRow()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

values(index: number, obj?:HttpColumnValue):HttpColumnValue|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new HttpColumnValue()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

valuesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startHttpRow(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addValues(builder:flatbuffers.Builder, valuesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, valuesOffset, 0);
}

static createValuesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startValuesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endHttpRow(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createHttpRow(builder:flatbuffers.Builder, valuesOffset:flatbuffers.Offset):flatbuffers.Offset {
  HttpRow.startHttpRow(builder);
  HttpRow.addValues(builder, valuesOffset);
  return HttpRow.endHttpRow(builder);
}
}
