// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class HttpColumnValue {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):HttpColumnValue {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsHttpColumnValue(bb:flatbuffers.ByteBuffer, obj?:HttpColumnValue):HttpColumnValue {
  return (obj || new HttpColumnValue()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsHttpColumnValue(bb:flatbuffers.ByteBuffer, obj?:HttpColumnValue):HttpColumnValue {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new HttpColumnValue()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

stringValue():string|null
stringValue(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
stringValue(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startHttpColumnValue(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addStringValue(builder:flatbuffers.Builder, stringValueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, stringValueOffset, 0);
}

static endHttpColumnValue(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createHttpColumnValue(builder:flatbuffers.Builder, stringValueOffset:flatbuffers.Offset):flatbuffers.Offset {
  HttpColumnValue.startHttpColumnValue(builder);
  HttpColumnValue.addStringValue(builder, stringValueOffset);
  return HttpColumnValue.endHttpColumnValue(builder);
}
}
