// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class Int64Value {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Int64Value {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsInt64Value(bb:flatbuffers.ByteBuffer, obj?:Int64Value):Int64Value {
  return (obj || new Int64Value()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsInt64Value(bb:flatbuffers.ByteBuffer, obj?:Int64Value):Int64Value {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Int64Value()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

v():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startInt64Value(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addV(builder:flatbuffers.Builder, v:bigint) {
  builder.addFieldInt64(0, v, BigInt('0'));
}

static endInt64Value(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createInt64Value(builder:flatbuffers.Builder, v:bigint):flatbuffers.Offset {
  Int64Value.startInt64Value(builder);
  Int64Value.addV(builder, v);
  return Int64Value.endInt64Value(builder);
}
}
