// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class NullValue {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):NullValue {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsNullValue(bb:flatbuffers.ByteBuffer, obj?:NullValue):NullValue {
  return (obj || new NullValue()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsNullValue(bb:flatbuffers.ByteBuffer, obj?:NullValue):NullValue {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new NullValue()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startNullValue(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endNullValue(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createNullValue(builder:flatbuffers.Builder):flatbuffers.Offset {
  NullValue.startNullValue(builder);
  return NullValue.endNullValue(builder);
}
}
