# Please keep in sync this file with rust/cubesql!

[target."x86_64-unknown-linux-gnu"]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target."aarch64-unknown-linux-gnu"]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
