apiVersion: v1
kind: Service
metadata:
  name: {{ include "cubejs.fullname" . }}
  labels:
    app.kubernetes.io/component: master
    {{- include "cubejs.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: http
      port: {{ .Values.config.apiPort }}
      targetPort: http
    {{- if .Values.config.sqlPort }}
    - name: sql
      port: {{ .Values.config.sqlPort }}
      targetPort: sql
    {{- end}}
  selector:
    app.kubernetes.io/component: master
    {{- include "cubejs.selectorLabels" . | nindent 4 }}
