version: '2.2'

services:
  cube:
    image: nginx:latest
    ports:
      - 4000:4000
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - cube_api_1
      - cube_api_2

  cube_api_1:
    restart: always
    image: cubejs/cube:v0.31.67
    environment:
      - CUBEJS_DB_TYPE=postgres
      - CUBEJS_DB_HOST=demo-db-examples.cube.dev
      - CUBEJS_DB_PORT=5432
      - CUBEJS_DB_NAME=ecom
      - CUBEJS_DB_USER=cube
      - CUBEJS_DB_PASS=12345
      - CUBEJS_CUBESTORE_HOST=cubestore_router
      # - CUBEJS_CACHE_AND_QUEUE_DRIVER=cubestore
      - CUBEJS_REDIS_URL=redis://redis:6379
      - CUBEJS_API_SECRET=SECRET
      - CUBEJS_LOG_LEVEL=info
    volumes:
      - .:/cube/conf
    depends_on:
      - cubestore_router
      - cube_refresh_worker
      - redis
      
  cube_api_2:
    restart: always
    image: cubejs/cube:v0.31.67
    environment:
      - CUBEJS_DB_TYPE=postgres
      - CUBEJS_DB_HOST=demo-db-examples.cube.dev
      - CUBEJS_DB_PORT=5432
      - CUBEJS_DB_NAME=ecom
      - CUBEJS_DB_USER=cube
      - CUBEJS_DB_PASS=12345
      - CUBEJS_CUBESTORE_HOST=cubestore_router
      # - CUBEJS_CACHE_AND_QUEUE_DRIVER=cubestore
      - CUBEJS_REDIS_URL=redis://redis:6379
      - CUBEJS_API_SECRET=SECRET
      - CUBEJS_LOG_LEVEL=info
    volumes:
      - .:/cube/conf
    depends_on:
      - cubestore_router
      - cube_refresh_worker
      - redis

  cube_refresh_worker:
    restart: always
    image: cubejs/cube:v0.31.67
    environment:
      - CUBEJS_DB_TYPE=postgres
      - CUBEJS_DB_HOST=demo-db-examples.cube.dev
      - CUBEJS_DB_PORT=5432
      - CUBEJS_DB_NAME=ecom
      - CUBEJS_DB_USER=cube
      - CUBEJS_DB_PASS=12345
      - CUBEJS_CUBESTORE_HOST=cubestore_router
      # - CUBEJS_CACHE_AND_QUEUE_DRIVER=cubestore
      - CUBEJS_REDIS_URL=redis://redis:6379
      - CUBEJS_API_SECRET=SECRET
      - CUBEJS_LOG_LEVEL=info
      - CUBEJS_REFRESH_WORKER=true
    volumes:
      - .:/cube/conf
    depends_on:
      - cubestore_router
      - redis

  cubestore_router:
    restart: always
    image: cubejs/cubestore:v0.31.67-arm64v8
    ports:
      - 3306:3306
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_PORT=9999
      - CUBESTORE_SERVER_NAME=cubestore_router:9999
    volumes:
      - .cubestore:/cube/data

  cubestore_worker_1:
    restart: always
    image: cubejs/cubestore:v0.31.67-arm64v8
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_SERVER_NAME=cubestore_worker_1:10001
      - CUBESTORE_WORKER_PORT=10001
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore:/cube/data
    depends_on:
      - cubestore_router

  cubestore_worker_2:
    restart: always
    image: cubejs/cubestore:v0.31.67-arm64v8
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_SERVER_NAME=cubestore_worker_2:10002
      - CUBESTORE_WORKER_PORT=10002
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore:/cube/data
    depends_on:
      - cubestore_router

  redis:
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    logging:
      driver: none
