version: '2.2'

services:
  materialize:
    image: materialize/materialized:v0.26.1
    ports:
      - 6875:6875

  seed:
    image: jbergknoff/postgresql-client
    volumes:
      - .:/seed
    entrypoint: ["sh", "seed/seed.sh"]
    depends_on:
      - materialize

  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_TYPE=materialize
      - CUBEJS_DB_HOST=materialize
      - CUBEJS_DB_PORT=6875
      - CUBEJS_DB_NAME=materialize
      - CUBEJS_DB_USER=materialize
      - CUBEJS_API_SECRET=SECRET
    volumes:
      - .:/cube/conf
    depends_on:
      - seed