version: '3'

services:
  server:
    image: us-central1-docker.pkg.dev/cube-devrel-team/apollo-server/server
    build:
      context: ./
      dockerfile: Dockerfile.server
    ports:
    - '4000:4000'
  gateway:
    image: us-central1-docker.pkg.dev/cube-devrel-team/apollo-server/gateway
    build:
      context: ./
      dockerfile: Dockerfile.gateway
    ports:
    - '4001:4001'
  router:
    image: ghcr.io/apollographql/router:v1.0.0
    ports:
      - '4002:4002'
    environment:
      - APOLLO_ROUTER_SUPERGRAPH_PATH=/graphql/supergraph.graphql
      - APOLLO_ROUTER_CONFIG_PATH=/graphql/router.yaml
    volumes:
      - ./graphql:/graphql:ro
