version: '2.2'

services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 3000:3000
    env_file: .env
    volumes:
      - .:/cube/conf

  mysql:
    platform: linux/x86_64
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ecom-mysql
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./datadir:/var/lib/mysql

  # query:
  #   image: cfmanteiga/alpine-bash-curl-jq
  #   depends_on:
  #     - cube
  #   volumes:
  #     - .:/query
  #   entrypoint: ["sh", "query/queries/run.sh"]
