version: '2.2'

services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 3000:3000
    env_file: .env
    volumes:
      - .:/cube/conf

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: localDB
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  query:
    image: cfmanteiga/alpine-bash-curl-jq
    depends_on:
      - cube
    volumes:
      - .:/query
    entrypoint: ["bash", "query/queries/run.sh"]
