version: '3'
services:
  cube:
    container_name: "cube"
    restart: "always"
    image: cubejs/cube
    ports:
      - 4000:4000  # Cube.js API and Developer Playground
      - 5432:5432  # Cube SQL API
    env_file: 
      - ./config/cube.env
    volumes:
      - .:/cube/conf
  
  postgres:
    container_name: "postgres"
    restart: "always"
    image: postgres
    env_file:
      - ./config/postgres.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
      - ./services/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 54320:5432

  metabase:
    container_name: "metabase"
    restart: "always"
    image: metabase/metabase
    env_file:
      - ./config/metabase.env
    depends_on:
      - postgres
    ports:
      - 3000:3000

# Volumes to persist data
volumes:
  postgres_volume:
