openapi: "3.0.0"
info:
  description: "Cube.js Swagger Schema"
  version: "1.0.0"
  title: "Cube.js"
paths:
  "/v1/meta":
    get:
      summary: "Load Metadata"
      # TODO: Doesn't work in rust code-gen
      # parameters:
      #   - in: query
      #     name: extended
      #     required: true
      #     schema:
      #       type: boolean
      #     description: You will receive extended response if this parameter is true
      description: ""
      operationId: "metaV1"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/V1MetaResponse"
        "4XX":
          description: "Request could not be completed"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/V1Error"
        "5XX":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/V1Error"
  "/v1/load":
    post:
      summary: "Load data via Cube JSON Query"
      operationId: "loadV1"
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/V1LoadRequest'
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/V1LoadResponse"
        "4XX":
          description: "Request could not be completed"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/V1Error"
        "5XX":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/V1Error"
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    V1CubeMetaJoin:
      type: "object"
      required:
        - name
        - relationship
      properties:
        name:
          type: "string"
        relationship:
          type: "string"
    V1CubeMetaSegment:
      type: "object"
      required:
        - name
        - title
        - shortTitle
      properties:
        name:
          type: "string"
        title:
          type: "string"
        description:
          type: "string"
        shortTitle:
          type: "string"
        meta:
          type: "object"
    V1CubeMetaDimensionGranularity:
      type: "object"
      required:
        - name
        - title
      properties:
        name:
          type: "string"
        title:
          type: "string"
        interval:
          type: "string"
        sql:
          type: "string"
        offset:
          type: "string"
        origin:
          type: "string"
    V1CubeMetaDimension:
      type: "object"
      required:
        - name
        - type
      properties:
        name:
          type: "string"
        title:
          type: "string"
        shortTitle:
          type: "string"
        description:
          type: "string"
        type:
          type: "string"
        aliasMember:
          description: "When dimension is defined in View, it keeps the original path: Cube.dimension"
          type: "string"
        granularities:
          type: array
          items:
            $ref: "#/components/schemas/V1CubeMetaDimensionGranularity"
        meta:
          type: "object"
    V1CubeMetaMeasure:
      type: "object"
      required:
        - name
        - type
      properties:
        name:
          type: "string"
        title:
          type: "string"
        shortTitle:
          type: "string"
        description:
          type: "string"
        type:
          type: "string"
        aggType:
          type: "string"
        meta:
          type: "object"
        aliasMember:
          description: "When measure is defined in View, it keeps the original path: Cube.measure"
          type: "string"
    V1CubeMetaFolder:
      type: "object"
      required:
        - name
        - members
      properties:
        name:
          type: "string"
        members:
          type: array
          items:
            type: "string"
    V1CubeMetaNestedFolder:
      type: "object"
      required:
        - name
        - members
      properties:
        name:
          type: "string"
        members:
          type: array
          items:
            type: "string"
            oneOf:
              - type: string
              - $ref: "#/components/schemas/V1CubeMetaNestedFolder"
    V1CubeMetaHierarchy:
      type: "object"
      required:
        - name
        - levels
      properties:
        name:
          type: "string"
        aliasMember:
          description: "When hierarchy is defined in Cube, it keeps the original path: Cube.hierarchy"
          type: "string"
        title:
          type: "string"
        levels:
          type: "array"
          items:
            type: "string"
    V1CubeMeta:
      type: "object"
      required:
        - name
        - type
        - measures
        - dimensions
        - segments
      properties:
        name:
          type: "string"
        title:
          type: "string"
        type:
          $ref: "#/components/schemas/V1CubeMetaType"
        meta:
          type: "object"
        description:
          type: "string"
        measures:
          type: "array"
          items:
            $ref: "#/components/schemas/V1CubeMetaMeasure"
        dimensions:
          type: "array"
          items:
            $ref: "#/components/schemas/V1CubeMetaDimension"
        segments:
          type: "array"
          items:
            $ref: "#/components/schemas/V1CubeMetaSegment"
        joins:
          type: "array"
          items:
            $ref: "#/components/schemas/V1CubeMetaJoin"
        folders:
          type: "array"
          items:
            $ref: "#/components/schemas/V1CubeMetaFolder"
        nestedFolders:
          type: "array"
          items:
            $ref: "#/components/schemas/V1CubeMetaNestedFolder"
        hierarchies:
          type: "array"
          items:
            $ref: "#/components/schemas/V1CubeMetaHierarchy"
    V1CubeMetaType:
      type: "string"
      description: Type of cube
      enum:
        - "cube"
        - "view"
    V1MetaResponse:
      type: "object"
      properties:
        cubes:
          type: "array"
          items:
            $ref: "#/components/schemas/V1CubeMeta"
        compilerId:
          type: "string"
    V1LoadResultAnnotation:
      type: "object"
      required:
        - measures
        - dimensions
        - segments
        - timeDimensions
      properties:
        measures:
          type: "object"
        dimensions:
          type: "object"
        segments:
          type: "object"
        timeDimensions:
          type: "object"
    V1LoadResultData:
      type: "object"
    V1LoadResult:
      type: "object"
      required:
        - annotation
        - data
      properties:
        dataSource:
          type: "string"
        annotation:
          $ref: "#/components/schemas/V1LoadResultAnnotation"
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/V1LoadResultData"
        refreshKeyValues:
          type: "array"
          items:
            type: "object"
    V1Error:
      type: "object"
      required:
        - "error"
      properties:
        error:
          type: "string"
    V1LoadResponse:
      type: "object"
      required:
        - results
      properties:
        pivotQuery:
          type: "object"
        slowQuery:
          type: "boolean"
        queryType:
          type: "string"
        results:
          type: "array"
          items:
            $ref: "#/components/schemas/V1LoadResult"
    V1LoadRequestQueryFilterLogicalAnd:
      type: "object"
      properties:
        and:
          type: "array"
          items:
            type: "object"
    V1LoadRequestQueryFilterLogicalOr:
      type: "object"
      properties:
        or:
          type: "array"
          items:
            type: "object"
    V1LoadRequestQueryFilterBase:
      type: "object"
      properties:
        member:
          type: "string"
        operator:
          type: "string"
        values:
          type: "array"
          items:
            type: "string"
    V1LoadRequestQueryTimeDimension:
      type: "object"
      required:
        - "dimension"
      properties:
        dimension:
          type: "string"
        granularity:
          type: "string"
        dateRange:
          type: "object"
          # Don't work in rust code-gen
          # oneOf:
          #   - type: "string"
          #   - type: "array"
          #     items:
          #       type: "string"
    V1LoadRequestQueryFilterItem:
      oneOf:
        - $ref: "#/components/schemas/V1LoadRequestQueryFilterBase"
        - $ref: "#/components/schemas/V1LoadRequestQueryFilterLogicalOr"
        - $ref: "#/components/schemas/V1LoadRequestQueryFilterLogicalAnd"
    V1LoadRequestQueryJoinSubquery:
      type: "object"
      properties:
        sql:
          type: "string"
        # TODO This is _always_ a member expression, maybe pass as parsed, without intermediate string?
        "on":
          type: "string"
        # TODO why string? it's enum
        joinType:
          type: "string"
        alias:
          type: "string"
      required:
        - sql
        - "on"
        - joinType
        - alias
    V1LoadRequestJoinHint:
      type: "array"
      items:
        type: "string"
    V1LoadRequestQuery:
      type: "object"
      properties:
        measures:
          type: "array"
          items:
            type: "string"
        dimensions:
          type: "array"
          items:
            type: "string"
        segments:
          type: "array"
          items:
            type: "string"
        timeDimensions:
          type: "array"
          items:
            $ref: "#/components/schemas/V1LoadRequestQueryTimeDimension"
        order:
          type: "array"
          items:
            type: "array"
            items:
              type: "string"
        limit:
          type: "integer"
          format: "int32"
        offset:
          type: "integer"
          format: "int32"
        filters:
          type: "array"
          items:
            $ref: "#/components/schemas/V1LoadRequestQueryFilterItem"
        ungrouped:
          type: "boolean"
        # vector of (subquery sql: string, join condition: member expression, join type: enum)
        # they will be added to end of joinQuery in BaseQuery, in same order as here
        subqueryJoins:
          type: "array"
          items:
            $ref: "#/components/schemas/V1LoadRequestQueryJoinSubquery"
        joinHints:
          type: "array"
          items:
            $ref: "#/components/schemas/V1LoadRequestJoinHint"
    V1LoadRequest:
      type: "object"
      properties:
        queryType:
          type: "string"
        query:
          type: "object"
          $ref: "#/components/schemas/V1LoadRequestQuery"
