// Fixture for the LIKE-escaping smoke test. The values are chosen so that a
// wildcard leaking out of a `contains` filter produces a visibly different
// result from a correctly escaped literal:
//
//   '%' escaped -> matches ids 1, 7      '%' leaked -> matches all 7
//   '_' escaped -> matches id 4          '_' leaked -> matches all 7
//
// Trino string literals do not process backslash escapes, so `back\slash`
// reaches the database with a single backslash.
//
// The two cubes are written out in full rather than sharing a spread member
// object on purpose: Cube's transpiler only rewrites `sql` properties into
// functions when they appear literally inside the `cube()` call, so members
// pulled in via a spread fail schema validation.
const ROWS = `
  SELECT 1 AS id, '50% off' AS name
  UNION ALL SELECT 2 AS id, 'discount 50 percent' AS name
  UNION ALL SELECT 3 AS id, 'no discount' AS name
  UNION ALL SELECT 4 AS id, 'a_b' AS name
  UNION ALL SELECT 5 AS id, 'axb' AS name
  UNION ALL SELECT 6 AS id, 'back\\slash' AS name
  UNION ALL SELECT 7 AS id, '100%' AS name
`;

// Queried straight against Trino - exercises the Presto/Trino dialect, which
// must emit `ESCAPE '\'` because Trino has no default LIKE escape character.
cube('LikeDirect', {
  sql: ROWS,
  measures: {
    count: {
      type: 'count',
    },
  },
  dimensions: {
    id: {
      sql: 'id',
      type: 'number',
      primaryKey: true,
    },
    name: {
      sql: 'name',
      type: 'string',
    },
  },
});

// Same data behind a pre-aggregation. A query answerable from the rollup is
// served by Cube Store, so the filter SQL is generated by the Cube Store
// dialect rather than the Trino one - a separate escaping path.
cube('LikeRollup', {
  sql: ROWS,
  measures: {
    count: {
      type: 'count',
    },
  },
  dimensions: {
    id: {
      sql: 'id',
      type: 'number',
      primaryKey: true,
    },
    name: {
      sql: 'name',
      type: 'string',
    },
  },
  preAggregations: {
    byName: {
      measures: [CUBE.count],
      dimensions: [CUBE.name],
      refreshKey: {
        every: '1 day',
      },
    },
  },
});
