name: Documentation Publish
on:
  push:
    paths:
      - '.github/workflows/docs.yml'
      - 'docs-gen/**'
      - 'docs/**'
    branches:
      - master
jobs:
  docs:
    name: Publish
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./docs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            docs/node_modules
          key: ${{ runner.os }}-workspace-docs-${{ matrix.node-version }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DOCS_DEPLOY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DOCS_DEPLOY_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Generate API documentation
        run: ./docs-gen.sh
      - name: Build Gatsby site
        run: ./deploy-production.sh
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
