name: Issue Labeler
on:
  issues:
    types: [labeled]

jobs:
  main:
    name: Process Label Action
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Process Label Action
        uses: hramos/label-actions@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
