on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: Build Latest - TransAI Cube
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download backend-native artifact
        uses: actions/download-artifact@v4
        with:
          name: "native-linux-x64-glibc-3.9.node"    # this name is referenced in above in native_linux
          path: ./packages/cubejs-backend-native/
      - name: Build & push
        uses: xip-online-applications/gha-workflow-templates/ghcr-build-push@main
        with:
          repository: '${{ github.repository }}/cube'
          tag: 'latest'
          context: ./
          dockerfile: ./packages/cubejs-docker/dev.Dockerfile
